### ISSUE TITLE
React-native 스타일을 scss로 적용해도 괜찮을까요?

### ISSUE THREAD

**Issue by jook-bob2** [grotesq/codelab-react-native-5th#73]
강의 정말 잘 봤습니다!
Global 스타일을 scss로 하는게 편한데 해도 무방할까요?
노드 라이브러리 검색해보니 react-native-sass-transformer, react-native-css-modules 이런 것들이 있던데,
추천 해주실만한 라이브러리가 혹시 있으실까요??

**Comment by unk** [comment]
RN에서는 sass를 사용해 본 적이 없어서 제가 추천을 드리기는 어렵겠지만, sass는 사용자 층이 두터우니 사용해보시는 것도 좋을 것 같습니다.
다만 웹에서처럼 글로벌 스타일시트 형태로 작성하기는 어려우실거고, 작성은 sass/scss로 하고 사용은 모듈 CSS 처럼 하는 것들이 대부분인 것 같습니다. 그런 부분들은 기존의 scss 사용하시는 경험과 다르실 수도 있으니 그런 부분을 중점적으로 테스트 해보시면 좋겠네요.

감사합니다 :)

**Comment by jook-bob2** [comment]
한번 적용해보고, 테스트 후에 적합한지 확인해 봐야겠네요.
감사합니다 !!
